<?php
    $language_config = array(
        'bg' => [
            'home'    => 'Начало',
            'profile' => 'Профил',
            'listing' => 'Членове',
            'auth'    => 'Вход/Регистрация',
            'sign-out'  => 'Изход',
            'settings'  => 'Настройки',
            'lang-pref' => 'Предпочитан език?',
            'email' => 'И-мейл',
            'user'  => 'Потребителско име',
            'pass'  => 'Парола',
            'pass-rep' => 'Потвърди паролата',
            'submit'   => 'Потвърди',
            'username-requirement' => 'Потребителското име трябва да съдържа минимум 3 и максимум 30 символа',
            'search'   => 'Търсене...',
            'sign-in'  => 'Вход',
            'sign-up'  => 'Стани член сега',
            'forgotten-password' => 'Забравена парола?',
            'recover-password'   => 'Възтановяване на парола',
            'posts'  => 'Отговори',
            'joined' => 'Присъединен/на',
            'last-visited' => 'Последно влизане',
            'admin' => 'Админ',
            'moderator' => 'Модератор',
            'member' => 'Член',
            'followers' => 'Последователи',
            'following' => 'Последвал/ла',
            'none' => 'Няма',
            'logo-color' => 'Смени цвета на логото',
            'info' => 'инфо',
            'accounts' => 'Акаунти',
            'bio' => 'Биография',
            'total-topics'  => 'Дискусии',
            'total-posts'   => 'Отговори',
            'last-post-by'  => 'Последен отговор',
            'newest-member' => 'Последно регистриран',
            'total' => 'Общо',
            'by' => 'От: ',
            'welcome' => 'Добре дошли, ',
            'login-errors' => [
                'empty' => 'Това поле е задължително!',
                'wrong-u-p' => 'Грешен потребител / парола!'
            ],
            'register-errors' => [
                'empty' => 'Това поле е задължително!',
                'existing-user'   => 'Потребителското име е заето!',
                'existing-email'  => 'E-mail адреса е зает!',
                'passwords-match' => 'Паролите не съвпадат!'
            ],
            'reset-pass-errors' => [
                'empty'   => 'Това поле е задължително!',
                'wrong-e' => 'Не съществува такъе e-mail!'
            ],
            'password-box' => [
                'header'   => 'Паролата трябва да има',
                'length'   => '&bull; Между 15 и 60 символа.',
                'alpha'    => '&bull; Поне една цифра и една главна буква.'
            ],
            "page-not-found" => "404 Страницата не е намерена",
            "page-forbidden" => "403 Достъпа забранен",
            'find-game' => 'Намери любимата си игра',
            'visit-collection' => 'или прегледай колекцията'
        ],
        'en' => [
            'home'    => 'Home',
            'profile' => 'Profile',
            'listing' => 'Members',
            'auth'    => 'Sign in/up',
            'sign-out'  => 'Sign out',
            'settings'  => 'Settings',
            'lang-pref' => 'Preferred language?',
            'email' => 'E-mail',
            'user'  => 'Username',
            'pass'  => 'Password',
            'pass-rep' => 'Confirm password',
            'submit'   => 'Submit',
            'username-requirement' => 'Username must contain atleast 3 characters and maximum 30 characters.',
            'search'   => 'Search...',
            'sign-in'  => 'Sign in',
            'sign-up'  => 'Sign up for free',
            'forgotten-password' => 'Forgot your password?',
            'recover-password'   => 'Password recovery',
            'posts'  => 'Posts',
            'joined' => 'Joined',
            'last-visited' => 'Last visited',
            'admin' => 'Admin',
            'moderator' => 'Moderator',
            'member' => 'Member',
            'followers' => 'Followers',
            'following' => 'Following',
            'none' => 'None',
            'logo-color' => 'Change logo color',
            'info' => 'Info',
            'accounts' => 'Accounts',
            'bio' => 'Bio',
            'total-topics'  => 'Topics',
            'total-posts'   => 'Posts',
            'last-post-by'  => 'Last post',
            'newest-member' => 'Last registered',
            'total' => 'Total',
            'by' => 'By: ',
            'welcome' => 'Welcome, ',
            'login-errors' => [
                'empty' => 'This field is required!',
                'wrong-u-p' => 'Wrong username / password!'
            ],
            'register-errors' => [
                'empty' => 'This field is required!',
                'existing-user'   => 'Username is already taken!',
                'existing-email'  => 'E-mail address is already taken!',
                'passwords-match' => 'Passwords do not match!'
            ],
            'reset-pass-errors' => [
                'empty'   => 'This field is required!',
                'wrong-e' => "Non-existent e-mail!"
            ],
            'password-box' => [
                'header' => 'Password must contain at least',
                'length' => '&bull; 15 to 60 characters.',
                'alpha'  => '&bull; One digit and one uppercase letter'
            ],
            "page-not-found" => "404 PAGE NOT FOUND",
            "page-forbidden" => "403 ACCESS PROHIBITED",
            'find-game' => 'Find your favourite game',
            'visit-collection' => 'or take a look at the collection'
        ]
    );
?>