<?php
    $language_config = array(
        'bg' => [
            'home'    => 'Начало',
            'profile' => 'Профил',
            'listing' => 'Членове',
            'auth'    => 'Вход/Регистрация',
            'sign-out'  => 'Изход',
            'settings'  => 'Настройки',
            'lang-pref' => 'Предпочитан език?',
            'email' => 'И-мейл',
            'user'  => 'Потребителско име',
            'pass'  => 'Парола',
            'pass-rep' => 'Потвърди паролата',
            'submit'   => 'Потвърди',
            'confirm-upload' => 'Потвърди',
            'pass-length'    => 'От 15 до 50 символа',
            'pass-char'      => 'Поне една главна буква',
            'pass-digit'     => 'Поне една цифра',
            'user-or-email'  => 'Потребителско име / И-мейл',
            'username-requirement' => 'Потребителското име трябва да съдържа от 3 до максимум 30 символа',
            'search'   => 'Търсене...',
            'sign-in'  => 'Вход',
            'sign-up'  => 'Стани член безплатно',
            'account-access-problem' => 'Не мога да вляза в акаунта си',
            'recover-password'   => 'Възтановяване на парола',
            'email-hint' => 'Въведи и-мейл на който да бъде изпратен линк</br> за възтановяването на паролата',
            'posts'  => 'Отговори',
            'joined' => 'Регистрация',
            'last-visited' => 'Последно влизане',
            'admin' => 'Админ',
            'moderator' => 'Модератор',
            'member'    => 'Член',
            'followers' => 'Последователи',
            'following' => 'Следвания',
            'follow'    => 'Следвай',
            'unfollow'     => 'Спри',
            'no-followers' => 'Този потребител все още няма последователи.',
            'uploads'      => 'Качвания',
            'none' => 'Няма',
            'logo-color' => 'Смени цвета на логото',
            'info' => 'Инфо',
            'accounts' => 'Акаунти',
            'bio' => 'Биография',
            'total-topics'  => 'Дискусии',
            'total-posts'   => 'Отговори',
            'last-post-by'  => 'Последен отговор',
            'newest-member' => 'Последно регистриран',
            'total' => 'Общо',
            'by' => 'От: ',
            'welcome' => 'Добре дошли, ',
            'write-comment' => 'Напиши коментар',
            'reply' => 'Отговор',
            'no-comments' => 'Все още няма коментари',
            'account-first' => 'Трябва да влезеш в акаунта си',
            'stats' => 'Статистики',
            'games' => 'Игри',
            'likes' => 'Харесвания',
            'comments' => 'Коментари',
            'login-to-comment' => 'Влез в акаунта си за да напишеш коментар',
            'quit-account-confirm' => 'Сигурен/а ли си че искаш да излезеш от акаунта си?',
            'under-development' => 'Страницата е в процес на разработване!',
            'upload-error'   => 'Проблем при качването на файла!',
            'upload-time'    => 'Трябва да минат 24 часа преди нов опит за качване на игра!',
            'upload-success' => 'Качването извършено успешно!</br>Предстои процес на обработване на заявката.',
            'yes' => 'Да',
            'no'  => 'Не',
            'most-liked-games' => 'Най-харесваните игри',
            'game-name'  => 'Име на играта',
            'game-genre' => 'Жанрове',
            'game-devs'  => 'Разработчици',
            'game-publ'  => 'Издатели',
            'game-date'  => 'Дати на издаване',
            'game-iso'   => 'Линк към iso файла',
            'game-pltf'  => 'Платформи',
            'examples'   => 'Примери',
            'add-link'   => 'Добави линк',
            'emojis'     => 'Емоджита',
            'filter-genre' => 'Филтър',
            'empty-fields' => 'Не всички полета са попълнени!',
            'platform-not-specified' => 'Не е избрана платформа!',
            'file-name-error' => 'Името на файла е невалидно!',
            'file-type-error' => 'Типа на файла е невалиден!',
            'file-size-error' => 'Размера на файла не трябва да надвишава %d байта!!',

            'rank-moderator' => 'Модератор',
            'rank-member'    => 'Член',

            'login-errors' => [
                'empty' => 'Това поле е задължително!',
                'wrong-u-p' => 'Грешен потребител / парола!',
                'wrong-p'   => 'Паролата е невалидна!'
            ],
            'register-errors' => [
                'empty-username'      => 'Полето за потребителско име е празно!',
                'empty-email'         => 'И-мейл полето е празно!',
                'empty-password'      => 'Полето за парола е празно!',
                'empty-password-conf' => 'Полето за потвърждение на паролата е празно!',
                'existing-user'   => 'Потребителското име е заето!',
                'username-format' => 'Потребителското име трябва да е с дължина [3, 30]!',
                'existing-email'  => 'E-mail адреса е зает!',
                'passwords-match' => 'Паролите не съвпадат!',
                'password-length' => 'Паролата трябва да е между 15 и 60 символа',
                'password-upper'  => 'Паролата трябва да съдържа поне една главна буква',
                'password-digit'  => 'Паролата трябва да съдържа поне една цифра'
            ],
            'reset-pass-errors' => [
                'empty'   => 'Това поле е задължително!',
                'wrong-e' => 'Не съществува такъе e-mail!'
            ],
            'password-box' => [
                'header'   => 'Паролата трябва да има',
                'length'   => '&bull; Между 15 и 60 символа.',
                'alpha'    => '&bull; Поне една цифра и една главна буква.'
            ],
            "page-not-found"   => "404 Страницата не е намерена",
            "page-forbidden"   => "403 Достъпа забранен",
            'find-favgame'     => 'Намери любимата си игра',
            'find-game'        => 'Намери игра',
            'search-members'   => 'Търси потребители',
            'visit-collection' => 'или прегледай колекцията',

            'account-settings' => 'Настройки на акаунта',
            'profile-picture'  => 'Профилна снимка',
            'overall-info'     => 'Обща информация',
            'login-location'   => 'Къде сте влезли',
            'social-media'     => 'Социални медии',
            'blocked-users'    => 'Блокирани потребители',
            'delete-account'   => 'Изтриване на акаунт',

            'display-name'     => 'Показно име',
            'location'         => 'Местоположение',
            'password-change'  => 'Промяна на паролата',
            'email-change'     => 'Промяна на и-мейла',
            'save-details'     => 'Запазване',

            'display-name-info' => 'Това е името което ще виждат другите потребители',
            'password-info'     => 'Добра идея е да използвате силна парола, която не използвате никъде другаде',
            'email-info'        => 'Имейла който ще се използва за обратна връзка',
            'location-info'     => 'Местоположението което ще се вижда в профила ви',
            
            'facebook-info'     => 'Потребителското име или id на акаунта',
            'instagram-info'    => 'Потребителското име в инстаграм',
            'twitter-info'      => 'Потребителското име в туитър',
            'youtube-info'      => 'Името на акаунта в youtube',
            'skype-info'        => 'Потребителското име в скайп',
            'account-deletion'  => 'Изтриването на акаунта е необратима стъпка и всички данни ще бъдат изтрити',

            'unblock-user'      => 'Отблокирай',
            'delete-account-confirmation' => 'Изтриване за постоянно ?',
            'profile-picture-update' => 'Смяна на профилната',
            'crop' => 'Изрежи',
            
            'new-display-name'     => 'Ново показно име',

            'current-password'     => 'Текуща парола',
            'new-password'         => 'Нова парола',
            'confirm-new-password' => 'Потвърди новата парола',

            'new-email' => 'Нов имейл'
        ],
        'en' => [
            'home'    => 'Home',
            'profile' => 'Profile',
            'listing' => 'Members',
            'auth'    => 'Sign in/up',
            'sign-out'  => 'Sign out',
            'settings'  => 'Settings',
            'lang-pref' => 'Preferred language?',
            'email' => 'E-mail',
            'user'  => 'Username',
            'pass'  => 'Password',
            'pass-rep' => 'Confirm password',
            'submit'   => 'Submit',
            'confirm-upload' => 'Confirm upload',
            'pass-length' => 'Minimum 15 up to 50 characters',
            'pass-char'   => 'At least one uppercase letter',
            'pass-digit'  => 'At least one digit',
            'user-or-email' => 'Username or E-mail',
            'username-requirement' => 'Username must contain atleast 3 up to 30 characters maximum.',
            'search'   => 'Search...',
            'sign-in'  => 'Sign in',
            'sign-up'  => 'Sign up for free',
            'account-access-problem' => 'I can\'t access my account',
            'recover-password'   => 'Password recovery',
            'email-hint' => 'Enter the e-mail to which the password recovery link will be sent',
            'posts'        => 'Posts',
            'joined'       => 'Joined',
            'last-visited' => 'Last visited',
            'admin'     => 'Admin',
            'moderator' => 'Moderator',
            'member'    => 'Member',
            'followers'    => 'Followers',
            'following'    => 'Following',
            'follow'       => 'Follow',
            'unfollow'     => 'Unfollow',
            'no-followers' => 'This user doesn\'t have any followers yet.',
            'uploads'      => 'Uploads',
            'none' => 'None',
            'logo-color' => 'Change logo color',
            'info' => 'Info',
            'accounts' => 'Accounts',
            'bio' => 'Bio',
            'total-topics'  => 'Topics',
            'total-posts'   => 'Posts',
            'last-post-by'  => 'Last post',
            'newest-member' => 'Last registered',
            'total' => 'Total',
            'by' => 'By: ',
            'welcome' => 'Welcome, ',
            'write-comment' => 'Post a comment',
            'reply' => 'Reply',
            'no-comments' => 'No comments yet',
            'account-first' => 'Login in to your account first',
            'stats' => 'Statistics',
            'games' => 'Games',
            'likes' => 'Likes',
            'comments' => 'Comments',
            'login-to-comment' => 'You need to login to post a comment',
            'quit-account-confirm' => 'Are you sure you want to sign out of your account?',
            'under-development' => 'This page is still under development!',
            'upload-error'    => 'Error uploading the file!',
            'upload-time'     => '24 hours must pass before next upload!',
            'upload-success'  => 'Upload successful, but it may take some time until its fully processed.',
            'file-name-error' => 'The name of the file is not valid!',
            'file-type-error' => 'The type of the file is not valid!',
            'file-size-error' => 'The size of the file must not exceed %d bytes!',

            'rank-moderator' => 'Moderator',
            'rank-member'    => 'Member',

            'yes' => 'Yes',
            'no'  => 'No',
            'most-liked-games' => 'Most liked games',
            'game-name'  => 'Name of the game',
            'game-genre' => 'Genres',
            'game-devs'  => 'Developers',
            'game-publ'  => 'Publishers',
            'game-date'  => 'Release dates',
            'game-iso'   => 'Link to iso',
            'game-pltf'  => 'Platforms',
            'examples'   => 'Examples',
            'add-link'   => 'Add link',
            'emojis'     => 'Emojis',
            'filter-genre' => 'Filter',
            'empty-fields' => 'Not all fields are filled!',
            'platform-not-specified' => 'Must choose a platform!',
            'login-errors'  => [
                'empty'     => 'This field is required!',
                'wrong-u-p' => 'Wrong username / password!',
                'wrong-p'   => 'Invalid password!'
            ],
            'register-errors' => [
                'empty-username'      => 'Username field is required!',
                'empty-email'         => 'E-mail field is required!',
                'empty-password'      => 'Password field is required!',
                'empty-password-conf' => 'Password confirmation field is required!',
                'existing-user'   => 'Username is already taken!',
                'username-format' => 'Username length must be in the range [3, 30]!',
                'existing-email'  => 'E-mail address is already taken!',
                'passwords-match' => 'Passwords do not match!',
                'password-length' => 'Password length must be in the range of 15 to 60 characters',
                'password-upper'  => 'Password must contain atleast one uppercase letter',
                'password-digit'  => 'Password must contain atleast one digit'
            ],
            'reset-pass-errors' => [
                'empty'   => 'This field is required!',
                'wrong-e' => "Non-existent e-mail!"
            ],
            'password-box' => [
                'header' => 'Password must contain at least',
                'length' => '&bull; 15 to 60 characters.',
                'alpha'  => '&bull; One digit and one uppercase letter'
            ],
            "page-not-found"   => "404 PAGE NOT FOUND",
            "page-forbidden"   => "403 ACCESS PROHIBITED",
            'find-favgame'     => 'Find your favourite game',
            'find-game'        => 'Search game',
            'search-members'   => 'Search members',
            'visit-collection' => 'or take a look at the collection',

            'account-settings' => 'Account settings',
            'profile-picture'  => 'Profile picture',
            'overall-info'     => 'Overall information',
            'login-location'   => 'Login location',
            'social-media'     => 'Social media',
            'blocked-users'    => 'Blocked users',
            'delete-account'   => 'Delete account',

            'display-name'     => 'Display name',
            'location'         => 'Location',
            'password-change'  => 'Change password',
            'email-change'     => 'Change e-mail',
            'save-details'     => 'Save details',

            'display-name-info' => 'This is the name that everyone will see',
            'password-info'     => 'It is a good idea to use a strong password, that you don\'t use anywhere else',
            'email-info'        => 'The email that is going to be used to contact you',
            'location-info'     => 'This is where you\'re located',
            
            'facebook-info'     => 'Your facebook id or username',
            'instagram-info'    => 'Your instagram username',
            'twitter-info'      => 'Your twitter username',
            'youtube-info'      => 'Your youtube account name',
            'skype-info'        => 'Your skype username',
            'account-deletion'  => 'Once you delete your account, there is no going back. Please be certain.',

            'unblock-user'      => 'Unblock user',
            'delete-account-confirmation' => 'Delete account permanently ?',
            'profile-picture-update' => 'Update profile picture',
            'crop' => 'Crop image',
            
            'new-display-name'     => 'New display name',

            'current-password'     => 'Current password',
            'new-password'         => 'New password',
            'confirm-new-password' => 'Confirm new password',

            'new-email' => 'New e-mail'
        ]
    );
?>